import React from 'react';
import { useAppContext } from '../../context/AppContext';
import jsPDF from "jspdf";
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip } from 'recharts';
import {
  TrendingUp,
  AlertTriangle,
  ShieldCheck,
  Thermometer,
  Brain
} from 'lucide-react';

const COLORS = ['#10b981', '#ef4444'];

const AnalyticsPanel = () => {

  const { stressResults } = useAppContext();

  const summary = stressResults?.summary;
  const prediction = stressResults?.prediction;

  if (!summary) {
    return (
      <div className="w-96 bg-white border-l border-slate-200 p-6 flex items-center justify-center">
        <p className="text-slate-500 text-sm">
          Run analysis to see field insights
        </p>
      </div>
    );
  }

  const healthScore = summary.health_score || 0;
  const stressPercent = summary.stress_percentage || 0;
  const areaUnderStress = summary.area_under_stress || 0;
  const confidenceScore = summary.confidence_score || 0;

  const temperatureProxy = (100 - healthScore).toFixed(2);

  const chartData = [
    { name: 'Healthy', value: healthScore },
    { name: 'Stressed', value: stressPercent }
  ];

  const isWorsening =
    prediction &&
    prediction.predicted_stress_next_7_days > stressPercent;

  const getRiskColor = (risk) => {
    if (risk === "High") return "text-red-600";
    if (risk === "Moderate") return "text-amber-600";
    return "text-green-600";
  };

  const downloadPDF = () => {

    if (!summary) return;
  
    const doc = new jsPDF();
  
    doc.setFontSize(18);
    doc.text("CropOrbit Field Report", 20, 20);
  
    doc.setFontSize(12);
    doc.text(`Date: ${new Date().toLocaleString()}`, 20, 30);
  
    doc.line(20, 35, 190, 35);
  
    doc.setFontSize(14);
    doc.text("Current Field Analysis", 20, 45);
  
    doc.setFontSize(12);
    doc.text(`Health Score: ${healthScore.toFixed(2)}%`, 20, 55);
    doc.text(`Stress Percentage: ${stressPercent.toFixed(2)}%`, 20, 65);
    doc.text(`Area Under Stress: ${areaUnderStress.toFixed(2)}%`, 20, 75);
    doc.text(`Confidence Score: ${confidenceScore.toFixed(2)}%`, 20, 85);
  
    if (prediction) {
      doc.setFontSize(14);
      doc.text("AI Forecast (7 Days)", 20, 100);
  
      doc.setFontSize(12);
      doc.text(
        `Predicted Stress: ${prediction.predicted_stress_next_7_days}%`,
        20,
        110
      );
      doc.text(`Risk Level: ${prediction.risk_level}`, 20, 120);
    }
  
    doc.setFontSize(10);
    doc.text(
      "Generated by CropOrbit - Satellite Powered Crop Intelligence",
      20,
      280
    );
  
    doc.save("CropOrbit_Report.pdf");
  };

  return (
    <div className="w-96 bg-white border-l border-slate-200 p-6 flex flex-col overflow-y-auto max-h-screen">

      {/* Premium Gradient Title */}
      <h2 className="text-lg font-bold bg-gradient-to-r from-agri-green to-emerald-500 bg-clip-text text-transparent mb-6">
        Field Analytics
      </h2>
      <button
        onClick={downloadPDF}
        className="mb-6 w-full bg-agri-green text-white py-2 rounded-lg hover:bg-agri-dark transition-colors text-sm font-semibold"
        >
        Download PDF Report
      </button>


      {/* Metric Cards */}
      <div className="grid grid-cols-2 gap-4 mb-8">

        <MetricCard
          icon={<TrendingUp size={16} className="text-agri-green" />}
          label="Health Score"
          value={`${healthScore.toFixed(2)}%`}
          color="text-agri-green"
        />

        <MetricCard
          icon={<AlertTriangle size={16} className="text-red-500" />}
          label="Stress %"
          value={`${stressPercent.toFixed(2)}%`}
          color="text-red-500"
        />

        <MetricCard
          icon={<AlertTriangle size={16} className="text-amber-500" />}
          label="Area Under Stress"
          value={`${areaUnderStress.toFixed(2)}%`}
          color="text-amber-500"
        />

        <div className="p-4 rounded-xl bg-slate-50 border">
          <div className="flex items-center gap-2 mb-2">
            <ShieldCheck size={16} className="text-indigo-500" />
            <p className="text-xs text-slate-500">Confidence Score</p>
          </div>

          <p className="text-2xl font-bold text-indigo-500">
            {confidenceScore.toFixed(2)}%
          </p>

          {/* Confidence Progress Bar */}
          <div className="mt-2 h-2 w-full bg-slate-200 rounded-full overflow-hidden">
            <div
              className="h-full bg-indigo-500 transition-all duration-500"
              style={{ width: `${confidenceScore}%` }}
            />
          </div>
        </div>

      </div>

      {/* 🔥 AI Forecast Section */}
      {prediction && (
        <div className="mb-8 p-5 rounded-xl bg-gradient-to-br from-slate-50 to-slate-100 border shadow-sm">
          <div className="flex items-center gap-2 mb-3">
            <Brain size={16} className="text-purple-600" />
            <p className="text-xs text-slate-500 uppercase tracking-wider">
              AI Forecast (7 Days)
            </p>
          </div>

          <p className="text-3xl font-bold text-purple-700">
            {prediction.predicted_stress_next_7_days}%
          </p>

          <p className={`text-sm font-semibold mt-1 ${getRiskColor(prediction.risk_level)}`}>
            Risk Level: {prediction.risk_level}
          </p>

          {isWorsening !== null && (
            <p className={`text-xs mt-2 ${isWorsening ? "text-red-500" : "text-green-600"}`}>
              {isWorsening ? "▲ Risk Increasing" : "▼ Condition Improving"}
            </p>
          )}

          <p className="text-xs text-slate-400 mt-3">
            Prediction based on vegetation trend and stress progression.
          </p>
        </div>
      )}

      {/* Pie Chart */}
      <div className="mb-8">
        <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-4">
          Health Distribution
        </h3>

        <ResponsiveContainer width="100%" height={250}>
          <PieChart>
            <Pie
              data={chartData}
              cx="50%"
              cy="50%"
              innerRadius={60}
              outerRadius={90}
              paddingAngle={3}
              dataKey="value"
            >
              {chartData.map((entry, index) => (
                <Cell key={`cell-${index}`} fill={COLORS[index]} />
              ))}
            </Pie>
            <Tooltip />
          </PieChart>
        </ResponsiveContainer>
      </div>

      {/* Thermal Indicator */}
      <div className="mt-auto p-4 rounded-xl bg-slate-50 border">
        <div className="flex items-center gap-2 mb-2">
          <Thermometer size={16} className="text-orange-500" />
          <p className="text-xs text-slate-500">Thermal Stress Indicator</p>
        </div>
        <p className="text-lg font-semibold text-orange-500">
          {temperatureProxy}% Relative Heat Risk
        </p>
        <p className="text-xs text-slate-400 mt-1">
          Derived from vegetation health anomaly
        </p>
      </div>

    </div>
  );
};

const MetricCard = ({ icon, label, value, color }) => (
  <div className="p-4 rounded-xl bg-slate-50 border">
    <div className="flex items-center gap-2 mb-2">
      {icon}
      <p className="text-xs text-slate-500">{label}</p>
    </div>
    <p className={`text-2xl font-bold ${color}`}>
      {value}
    </p>
  </div>
);

export default AnalyticsPanel;